---
title: "06-Conclusion"
author: "John Gilheany"
date: "9/13/2017"
output: html_document
---

# Conclusion  
All in all, the 4 models were comprable in terms of statistical resiliency and predictive power. Each model may have a different usage, based of each model's strengths and weaknesses, and what goals the investor has in mind for the model. For example, an investor looking to capture an arbitrage opportunity in November, might be best suited in looking at the November specific model. Someone looking for abritrage opportunities throughout the year during both rebalances might look at the combined May and November model. 

## Side by Side Model Comparison 
```{r, echo=FALSE}
library(broom)
library(tidyr)
all_models <- rbind_list(
    tidy(logit1) %>% mutate(model = 1),
    tidy(logit2) %>% mutate(model = 2),
    tidy(logit3) %>% mutate(model = 3), 
    tidy(logit4) %>% mutate(model = 4))

ols_table <- all_models %>%
    select(-statistic, -p.value) %>%
    mutate_each(funs(round(., 2)), -term) %>% 
    gather(key, value, estimate:std.error) %>%
    spread(model, value) 

ols_table
```

## Model 1: Entire Data Set (Monthly)
In this model, the variables beta and index_before were found to be statistically significant, while the variables volatility and price to book ratio were found to not be statistically significant. 

## Model 2: Monthly

## Model 3: Panel Regression

# Discussion
After comparing all of the models....

