# Find unique minvol companies - Count 302
unique_minvol <- unique(data.frame(minvol$Ticker))
names(unique_minvol)[1]<-paste("Ticker")

# Find unique USA companies - Count 876
unique_usa <- unique(data.frame(usa$Ticker))
names(unique_usa)[1]<-paste("Ticker")

# Merge two
combo <- rbind(unique_minvol, unique_usa)

# Find unique elements in each
combo_unique <- unique(data.frame(combo$Ticker))
View(combo_unique)
# Combo has 876 unique elements. Means all USMV stocks in EUSA

# Extract unique elements from Min Vol to text to put in WRDS
write.csv(unique_minvol, "inst/extdata/unique_minvol.csv")

# read in datum CSV (raw file)
# Load libraries
library(dplyr)
library(lubridate)
library(PerformanceAnalytics)

#read datum
unique_minvol_ticker_information <- read.csv("inst/extdata/unique_minvol_ticker_information.csv")

# Covert Dates into Date format
unique_minvol_ticker_information$date <- ymd(unique_minvol_ticker_information$date)

# Rename column names to be consistent with prior formats
names(unique_minvol_ticker_information)[1]<-paste("Date")
names(unique_minvol_ticker_information)[2]<-paste("Ticker")
names(unique_minvol_ticker_information)[3]<-paste("Price")

# Filter by various Min Vol tickers (took out ones with numbers)
MMM <- filter(unique_minvol_ticker_information, Ticker == "MMM")
ABT <- filter(unique_minvol_ticker_information, Ticker == "ABT")
ABBV <- filter(unique_minvol_ticker_information, Ticker == "ABBV")
ACN <- filter(unique_minvol_ticker_information, Ticker == "ACN")
CB <- filter(unique_minvol_ticker_information, Ticker == "CB")
ACE <- filter(unique_minvol_ticker_information, Ticker == "ACE")
ACT <- filter(unique_minvol_ticker_information, Ticker == "ACT")
ATVI <- filter(unique_minvol_ticker_information, Ticker == "ATVI")
ADBE <- filter(unique_minvol_ticker_information, Ticker == "ADBE")
AAP <- filter(unique_minvol_ticker_information, Ticker == "AAP")
AET <- filter(unique_minvol_ticker_information, Ticker == "AET")
GAS <- filter(unique_minvol_ticker_information, Ticker == "GAS")
AGNC <- filter(unique_minvol_ticker_information, Ticker == "AGNC")
Y <- filter(unique_minvol_ticker_information, Ticker == "Y")
AGN <- filter(unique_minvol_ticker_information, Ticker == "AGN")
ALL <- filter(unique_minvol_ticker_information, Ticker == "ALL")
GOOGL <- filter(unique_minvol_ticker_information, Ticker == "GOOGL")
GOOG <- filter(unique_minvol_ticker_information, Ticker == "GOOG")
ALTR <- filter(unique_minvol_ticker_information, Ticker == "ALTR")
MO <- filter(unique_minvol_ticker_information, Ticker == "MO")
AEP <- filter(unique_minvol_ticker_information, Ticker == "AEP")
AMT <- filter(unique_minvol_ticker_information, Ticker == "AMT")
AWK <- filter(unique_minvol_ticker_information, Ticker == "AWK")
ABC <- filter(unique_minvol_ticker_information, Ticker == "ABC")
AMGN <- filter(unique_minvol_ticker_information, Ticker == "AMGN")
APH <- filter(unique_minvol_ticker_information, Ticker == "APH")
NLY <- filter(unique_minvol_ticker_information, Ticker == "NLY")
ANSS <- filter(unique_minvol_ticker_information, Ticker == "ANSS")
AR <- filter(unique_minvol_ticker_information, Ticker == "AR")
ANTM <- filter(unique_minvol_ticker_information, Ticker == "ANTM")
AON <- filter(unique_minvol_ticker_information, Ticker == "AON")
AAPL <- filter(unique_minvol_ticker_information, Ticker == "AAPL")
ARMK <- filter(unique_minvol_ticker_information, Ticker == "ARMK")
ACGL <- filter(unique_minvol_ticker_information, Ticker == "ACGL")
T <- filter(unique_minvol_ticker_information, Ticker == "T")
ADP <- filter(unique_minvol_ticker_information, Ticker == "ADP")
AZO <- filter(unique_minvol_ticker_information, Ticker == "AZO")
AVB <- filter(unique_minvol_ticker_information, Ticker == "AVB")
AXS <- filter(unique_minvol_ticker_information, Ticker == "AXS")
BXLT <- filter(unique_minvol_ticker_information, Ticker == "BXLT")
BAX <- filter(unique_minvol_ticker_information, Ticker == "BAX")
BDX <- filter(unique_minvol_ticker_information, Ticker == "BDX")
BBBY <- filter(unique_minvol_ticker_information, Ticker == "BBBY")
BRKB <- filter(unique_minvol_ticker_information, Ticker == "BRKB")
BIIB<- filter(unique_minvol_ticker_information, Ticker == "BIIB")
BLKFDS<- filter(unique_minvol_ticker_information, Ticker == "BLKFDS")
BMC<- filter(unique_minvol_ticker_information, Ticker == "BMC")
BXP<- filter(unique_minvol_ticker_information, Ticker == "BXP")
BSX<- filter(unique_minvol_ticker_information, Ticker == "BSX")
BMY<- filter(unique_minvol_ticker_information, Ticker == "BMY")
BRX<- filter(unique_minvol_ticker_information, Ticker == "BRX")
BR<- filter(unique_minvol_ticker_information, Ticker == "BR")
BCR<- filter(unique_minvol_ticker_information, Ticker == "BCR")
CA<- filter(unique_minvol_ticker_information, Ticker == "CA")
COG<- filter(unique_minvol_ticker_information, Ticker == "COG")
CDNS<- filter(unique_minvol_ticker_information, Ticker == "CDNS")
CRC<- filter(unique_minvol_ticker_information, Ticker == "CRC")
CPT<- filter(unique_minvol_ticker_information, Ticker == "CPT")
CPB<- filter(unique_minvol_ticker_information, Ticker == "CPB")
CAH<- filter(unique_minvol_ticker_information, Ticker == "CAH")
CELG<- filter(unique_minvol_ticker_information, Ticker == "CELG")
CTL<- filter(unique_minvol_ticker_information, Ticker == "CTL")
CHRW<- filter(unique_minvol_ticker_information, Ticker == "CHRW")
CHTR<- filter(unique_minvol_ticker_information, Ticker == "CHTR")
CVX<- filter(unique_minvol_ticker_information, Ticker == "CVX")
CMG<- filter(unique_minvol_ticker_information, Ticker == "CMG")
CHD<- filter(unique_minvol_ticker_information, Ticker == "CHD")
CI<- filter(unique_minvol_ticker_information, Ticker == "CI")
CINF<- filter(unique_minvol_ticker_information, Ticker == "CINF")
CTAS<- filter(unique_minvol_ticker_information, Ticker == "CTAS")
CSCO<- filter(unique_minvol_ticker_information, Ticker == "CSCO")
CLX<- filter(unique_minvol_ticker_information, Ticker == "CLX")
CME<- filter(unique_minvol_ticker_information, Ticker == "CME")
KO<- filter(unique_minvol_ticker_information, Ticker == "KO")
COLE<- filter(unique_minvol_ticker_information, Ticker == "COLE")
CL<- filter(unique_minvol_ticker_information, Ticker == "CL")
CMCSA<- filter(unique_minvol_ticker_information, Ticker == "CMCSA")
CMCSK<- filter(unique_minvol_ticker_information, Ticker == "CMCSK")
CAG<- filter(unique_minvol_ticker_information, Ticker == "CAG")
COP<- filter(unique_minvol_ticker_information, Ticker == "COP")
ED<- filter(unique_minvol_ticker_information, Ticker == "ED")
STZ<- filter(unique_minvol_ticker_information, Ticker == "STZ")
COO<- filter(unique_minvol_ticker_information, Ticker == "COO")
COST<- filter(unique_minvol_ticker_information, Ticker == "COST")
COV<- filter(unique_minvol_ticker_information, Ticker == "COV")
CCI<- filter(unique_minvol_ticker_information, Ticker == "CCI")
CVS<- filter(unique_minvol_ticker_information, Ticker == "CVS")
DHR<- filter(unique_minvol_ticker_information, Ticker == "DHR")
DRI<- filter(unique_minvol_ticker_information, Ticker == "DRI")
DVA<- filter(unique_minvol_ticker_information, Ticker == "DVA")
DE<- filter(unique_minvol_ticker_information, Ticker == "DE")
DLR<- filter(unique_minvol_ticker_information, Ticker == "DLR")
DTV<- filter(unique_minvol_ticker_information, Ticker == "DTV")
DG<- filter(unique_minvol_ticker_information, Ticker == "DG")
DLTR<- filter(unique_minvol_ticker_information, Ticker == "DLTR")
D<- filter(unique_minvol_ticker_information, Ticker == "D")
DPS<- filter(unique_minvol_ticker_information, Ticker == "DPS")
DUK<- filter(unique_minvol_ticker_information, Ticker == "DUK")
DNB<- filter(unique_minvol_ticker_information, Ticker == "DNB")
DD<- filter(unique_minvol_ticker_information, Ticker == "DD")
EBAY<- filter(unique_minvol_ticker_information, Ticker == "EBAY")
ECL<- filter(unique_minvol_ticker_information, Ticker == "ECL")
EW<- filter(unique_minvol_ticker_information, Ticker == "EW")
LLY<- filter(unique_minvol_ticker_information, Ticker == "LLY")
EMC<- filter(unique_minvol_ticker_information, Ticker == "EMC")
EGN<- filter(unique_minvol_ticker_information, Ticker == "EGN")
EQT<- filter(unique_minvol_ticker_information, Ticker == "EQT")
EFX<- filter(unique_minvol_ticker_information, Ticker == "EFX")
EQR<- filter(unique_minvol_ticker_information, Ticker == "EQR")
ESS<- filter(unique_minvol_ticker_information, Ticker == "ESS")
RE<- filter(unique_minvol_ticker_information, Ticker == "RE")
ES<- filter(unique_minvol_ticker_information, Ticker == "ES")
EXPD<- filter(unique_minvol_ticker_information, Ticker == "EXPD")
ESRX<- filter(unique_minvol_ticker_information, Ticker == "ESRX")
EXR<- filter(unique_minvol_ticker_information, Ticker == "EXR")
XOM<- filter(unique_minvol_ticker_information, Ticker == "XOM")
FB<- filter(unique_minvol_ticker_information, Ticker == "FB")
FDO<- filter(unique_minvol_ticker_information, Ticker == "FDO")
FRT<- filter(unique_minvol_ticker_information, Ticker == "FRT")
FNF<- filter(unique_minvol_ticker_information, Ticker == "FNF")
FIS<- filter(unique_minvol_ticker_information, Ticker == "FIS")
FRC<- filter(unique_minvol_ticker_information, Ticker == "FRC")
FISV<- filter(unique_minvol_ticker_information, Ticker == "FISV")
FL<- filter(unique_minvol_ticker_information, Ticker == "FL")
FRX<- filter(unique_minvol_ticker_information, Ticker == "FRX")
FTV<- filter(unique_minvol_ticker_information, Ticker == "FTV")
FTR<- filter(unique_minvol_ticker_information, Ticker == "FTR")
IT<- filter(unique_minvol_ticker_information, Ticker == "IT")
GD<- filter(unique_minvol_ticker_information, Ticker == "GD")
GGP<- filter(unique_minvol_ticker_information, Ticker == "GGP")
GIS<- filter(unique_minvol_ticker_information, Ticker == "GIS")
GPC<- filter(unique_minvol_ticker_information, Ticker == "GPC")
GILD<- filter(unique_minvol_ticker_information, Ticker == "GILD")
GR<- filter(unique_minvol_ticker_information, Ticker == "GR")
HNZ<- filter(unique_minvol_ticker_information, Ticker == "HNZ")
HCP<- filter(unique_minvol_ticker_information, Ticker == "HCP")
HCN<- filter(unique_minvol_ticker_information, Ticker == "HCN")
HSIC<- filter(unique_minvol_ticker_information, Ticker == "HSIC")
HSY<- filter(unique_minvol_ticker_information, Ticker == "HSY")
HOLX<- filter(unique_minvol_ticker_information, Ticker == "HOLX")
HD<- filter(unique_minvol_ticker_information, Ticker == "HD")
HRL<- filter(unique_minvol_ticker_information, Ticker == "HRL")
HUM<- filter(unique_minvol_ticker_information, Ticker == "HUM")
IHS<- filter(unique_minvol_ticker_information, Ticker == "IHS")
INCO<- filter(unique_minvol_ticker_information, Ticker == "INCO")
INTC<- filter(unique_minvol_ticker_information, Ticker == "INTC")
IBM<- filter(unique_minvol_ticker_information, Ticker == "IBM")
INTU<- filter(unique_minvol_ticker_information, Ticker == "INTU")
ISRG<- filter(unique_minvol_ticker_information, Ticker == "ISRG")
JBHT<- filter(unique_minvol_ticker_information, Ticker == "JBHT")
SJM<- filter(unique_minvol_ticker_information, Ticker == "SJM")
JNJ<- filter(unique_minvol_ticker_information, Ticker == "JNJ")
K<- filter(unique_minvol_ticker_information, Ticker == "K")
KMB<- filter(unique_minvol_ticker_information, Ticker == "KMB")
KMI<- filter(unique_minvol_ticker_information, Ticker == "KMI")
KMR<- filter(unique_minvol_ticker_information, Ticker == "KMR")
KRFT<- filter(unique_minvol_ticker_information, Ticker == "KRFT")
KFT<- filter(unique_minvol_ticker_information, Ticker == "KFT")
LB<- filter(unique_minvol_ticker_information, Ticker == "LB")
LH<- filter(unique_minvol_ticker_information, Ticker == "LH")
LIFE<- filter(unique_minvol_ticker_information, Ticker == "LIFE")
LLTC<- filter(unique_minvol_ticker_information, Ticker == "LLTC")
LMT<- filter(unique_minvol_ticker_information, Ticker == "LMT")
LOM<- filter(unique_minvol_ticker_information, Ticker == "LOM")
LO<- filter(unique_minvol_ticker_information, Ticker == "LO")
LOW<- filter(unique_minvol_ticker_information, Ticker == "LOW")
MTB<- filter(unique_minvol_ticker_information, Ticker == "MTB")
MAC<- filter(unique_minvol_ticker_information, Ticker == "MAC")
MNK<- filter(unique_minvol_ticker_information, Ticker == "MNK")
MKL<- filter(unique_minvol_ticker_information, Ticker == "MKL")
MMC<- filter(unique_minvol_ticker_information, Ticker == "MMC")
MA<- filter(unique_minvol_ticker_information, Ticker == "MA")
MAT<- filter(unique_minvol_ticker_information, Ticker == "MAT")
MKC<- filter(unique_minvol_ticker_information, Ticker == "MKC")
MCD<- filter(unique_minvol_ticker_information, Ticker == "MCD")
MCK<- filter(unique_minvol_ticker_information, Ticker == "MCK")
MDT<- filter(unique_minvol_ticker_information, Ticker == "MDT")
MRK<- filter(unique_minvol_ticker_information, Ticker == "MRK")
MSFT<- filter(unique_minvol_ticker_information, Ticker == "MSFT")
KTF<- filter(unique_minvol_ticker_information, Ticker == "KTF")
MDLZ<- filter(unique_minvol_ticker_information, Ticker == "MDLZ")
MON<- filter(unique_minvol_ticker_information, Ticker == "MON")
MSI<- filter(unique_minvol_ticker_information, Ticker == "MSI")
NNN<- filter(unique_minvol_ticker_information, Ticker == "NNN")
NEM<- filter(unique_minvol_ticker_information, Ticker == "NEM")
NWSA<- filter(unique_minvol_ticker_information, Ticker == "NWSA")
NEE<- filter(unique_minvol_ticker_information, Ticker == "NEE")
NLSN<- filter(unique_minvol_ticker_information, Ticker == "NLSN")
NKE<- filter(unique_minvol_ticker_information, Ticker == "NKE")
JWN<- filter(unique_minvol_ticker_information, Ticker == "JWN")
NOC<- filter(unique_minvol_ticker_information, Ticker == "NOC")
NST<- filter(unique_minvol_ticker_information, Ticker == "NST")
ORLY<- filter(unique_minvol_ticker_information, Ticker == "ORLY")
OXY<- filter(unique_minvol_ticker_information, Ticker == "OXY")
OCR<- filter(unique_minvol_ticker_information, Ticker == "OCR")
OMC<- filter(unique_minvol_ticker_information, Ticker == "OMC")
ORCL<- filter(unique_minvol_ticker_information, Ticker == "ORCL")
PRE<- filter(unique_minvol_ticker_information, Ticker == "PRE")
PDCO<- filter(unique_minvol_ticker_information, Ticker == "PDCO")
PAYX<- filter(unique_minvol_ticker_information, Ticker == "PAYX")
PYPL<- filter(unique_minvol_ticker_information, Ticker == "PYPL")
PBCT<- filter(unique_minvol_ticker_information, Ticker == "PBCT")
POM<- filter(unique_minvol_ticker_information, Ticker == "POM")
PEP<- filter(unique_minvol_ticker_information, Ticker == "PEP")
PRGO<- filter(unique_minvol_ticker_information, Ticker == "PRGO")
PETM<- filter(unique_minvol_ticker_information, Ticker == "PETM")
PFE<- filter(unique_minvol_ticker_information, Ticker == "PFE")
PCG<- filter(unique_minvol_ticker_information, Ticker == "PCG")
PM<- filter(unique_minvol_ticker_information, Ticker == "PM")
PSX<- filter(unique_minvol_ticker_information, Ticker == "PSX")
PX<- filter(unique_minvol_ticker_information, Ticker == "PX")
PCP<- filter(unique_minvol_ticker_information, Ticker == "PCP")
PG<- filter(unique_minvol_ticker_information, Ticker == "PG")
PGN<- filter(unique_minvol_ticker_information, Ticker == "PGN")
PGR<- filter(unique_minvol_ticker_information, Ticker == "PGR")
PSA<- filter(unique_minvol_ticker_information, Ticker == "PSA")
QCI<- filter(unique_minvol_ticker_information, Ticker == "QCI")
QCOM<- filter(unique_minvol_ticker_information, Ticker == "QCOM")
DGX<- filter(unique_minvol_ticker_information, Ticker == "DGX")
Q<- filter(unique_minvol_ticker_information, Ticker == "Q")
RRC<- filter(unique_minvol_ticker_information, Ticker == "RRC")
RTN<- filter(unique_minvol_ticker_information, Ticker == "RTN")
O<- filter(unique_minvol_ticker_information, Ticker == "O")
REG<- filter(unique_minvol_ticker_information, Ticker == "REG")
RNR<- filter(unique_minvol_ticker_information, Ticker == "RNR")
RSG<- filter(unique_minvol_ticker_information, Ticker == "RSG")
RMD<- filter(unique_minvol_ticker_information, Ticker == "RMD")
RAI<- filter(unique_minvol_ticker_information, Ticker == "RAI")
ROST<- filter(unique_minvol_ticker_information, Ticker == "ROST")
MHFI<- filter(unique_minvol_ticker_information, Ticker == "MHFI")
LDOS<- filter(unique_minvol_ticker_information, Ticker == "LDOS")
SBAC<- filter(unique_minvol_ticker_information, Ticker == "SBAC")
SLB<- filter(unique_minvol_ticker_information, Ticker == "SLB")
SNI<- filter(unique_minvol_ticker_information, Ticker == "SNI")
SRE<- filter(unique_minvol_ticker_information, Ticker == "SRE")
SHW<- filter(unique_minvol_ticker_information, Ticker == "SHW")
SIAL<- filter(unique_minvol_ticker_information, Ticker == "SIAL")
SPG<- filter(unique_minvol_ticker_information, Ticker == "SPG")
SO<- filter(unique_minvol_ticker_information, Ticker == "SO")
LUV<- filter(unique_minvol_ticker_information, Ticker == "LUV")
SE<- filter(unique_minvol_ticker_information, Ticker == "SE")
STJ<- filter(unique_minvol_ticker_information, Ticker == "STJ")
SBUX<- filter(unique_minvol_ticker_information, Ticker == "SBUX")
SRCL<- filter(unique_minvol_ticker_information, Ticker == "SRCL")
SYK<- filter(unique_minvol_ticker_information, Ticker == "SYK")
SYMC<- filter(unique_minvol_ticker_information, Ticker == "SYMC")
SNPS<- filter(unique_minvol_ticker_information, Ticker == "SNPS")
SYY<- filter(unique_minvol_ticker_information, Ticker == "SYY")
TGT<- filter(unique_minvol_ticker_information, Ticker == "TGT")
TXN<- filter(unique_minvol_ticker_information, Ticker == "TXN")
TMO<- filter(unique_minvol_ticker_information, Ticker == "TMO")
TJX<- filter(unique_minvol_ticker_information, Ticker == "TJX")
TSS<- filter(unique_minvol_ticker_information, Ticker == "TSS")
TRV<- filter(unique_minvol_ticker_information, Ticker == "TRV")
UDR<- filter(unique_minvol_ticker_information, Ticker == "UDR")
ULTA<- filter(unique_minvol_ticker_information, Ticker == "ULTA")
UNP<- filter(unique_minvol_ticker_information, Ticker == "UNP")
UPS<- filter(unique_minvol_ticker_information, Ticker == "UPS")
UTX<- filter(unique_minvol_ticker_information, Ticker == "UTX")
UNH<- filter(unique_minvol_ticker_information, Ticker == "UNH")
UHS<- filter(unique_minvol_ticker_information, Ticker == "UHS")
USB<- filter(unique_minvol_ticker_information, Ticker == "USB")
USD<- filter(unique_minvol_ticker_information, Ticker == "USD")
VAL<- filter(unique_minvol_ticker_information, Ticker == "VAL")
VNTV<- filter(unique_minvol_ticker_information, Ticker == "VNTV")
VAR<- filter(unique_minvol_ticker_information, Ticker == "VAR")
VTR<- filter(unique_minvol_ticker_information, Ticker == "VTR")
VRSN<- filter(unique_minvol_ticker_information, Ticker == "VRSN")
VRSK<- filter(unique_minvol_ticker_information, Ticker == "VRSK")
VZ<- filter(unique_minvol_ticker_information, Ticker == "VZ")
VFC<- filter(unique_minvol_ticker_information, Ticker == "VFC")
VISA<- filter(unique_minvol_ticker_information, Ticker == "VISA")
V<- filter(unique_minvol_ticker_information, Ticker == "V")
VMW<- filter(unique_minvol_ticker_information, Ticker == "VMW")
VNO<- filter(unique_minvol_ticker_information, Ticker == "VNO")
WMT<- filter(unique_minvol_ticker_information, Ticker == "WMT")
DIS<- filter(unique_minvol_ticker_information, Ticker == "DIS")
WCN<- filter(unique_minvol_ticker_information, Ticker == "WCN")
WM<- filter(unique_minvol_ticker_information, Ticker == "WM")
WAT<- filter(unique_minvol_ticker_information, Ticker == "WAT")
WPI<- filter(unique_minvol_ticker_information, Ticker == "WPI")
WEC<- filter(unique_minvol_ticker_information, Ticker == "WEC")
WFC<- filter(unique_minvol_ticker_information, Ticker == "WFC")
WR<- filter(unique_minvol_ticker_information, Ticker == "WR")
WSH<- filter(unique_minvol_ticker_information, Ticker == "WSH")
WLTW<- filter(unique_minvol_ticker_information, Ticker == "WLTW")
WIN<- filter(unique_minvol_ticker_information, Ticker == "WIN")
WRB<- filter(unique_minvol_ticker_information, Ticker == "WRB")
GWW<- filter(unique_minvol_ticker_information, Ticker == "GWW")
XEL<- filter(unique_minvol_ticker_information, Ticker == "XEL")
YHOO<- filter(unique_minvol_ticker_information, Ticker == "YHOO")
YUM<- filter(unique_minvol_ticker_information, Ticker == "YUM")
ZAYO<- filter(unique_minvol_ticker_information, Ticker == "ZAYO")
ZBH<- filter(unique_minvol_ticker_information, Ticker == "ZBH")
ZTS<- filter(unique_minvol_ticker_information, Ticker == "ZTS")

# Calculate individual 252-day rolling SDs
MMM$SD <- rollingSD(MMM$Price, h = 252)
ABT$SD <- rollingSD(ABT$Price, h = 252)
ABBV$SD <- rollingSD(ABBV$Price, h = 252)
ACN$SD <- rollingSD(ACN$Price, h = 252)
CB$SD <- rollingSD(CB$Price, h = 252)
ACE$SD <- rollingSD(ACE$Price, h = 252)
ACT$SD <- rollingSD(ACT$Price, h = 252)
ATVI$SD <- rollingSD(ATVI$Price, h = 252)
ADBE$SD <- rollingSD(ADBE$Price, h = 252)
AAP$SD <- rollingSD(AAP$Price, h = 252)
AET$SD <- rollingSD(AET$Price, h = 252)
GAS$SD <- rollingSD(GAS$Price, h = 252)
AGNC$SD <- rollingSD(AGNC$Price, h = 252)
Y$SD <- rollingSD(Y$Price, h = 252)
AGN$SD <- rollingSD(AGN$Price, h = 252)
ALL$SD <- rollingSD(ALL$Price, h = 252)
GOOGL$SD <- rollingSD(GOOGL$Price, h = 252)
GOOG$SD <- rollingSD(GOOG$Price, h = 252)
ALTR$SD <- rollingSD(ALTR$Price, h = 252)
MO$SD <- rollingSD(MO$Price, h = 252)
AEP$SD <- rollingSD(AEP$Price, h = 252)
AMT$SD <- rollingSD(AMT$Price, h = 252)
AWK$SD <- rollingSD(AWK$Price, h = 252)
ABC$SD <- rollingSD(ABC$Price, h = 252)
AMGN$SD <- rollingSD(AMGN$Price, h = 252)
APH$SD <- rollingSD(APH$Price, h = 252)
NLY$SD <- rollingSD(NLY$Price, h = 252)
ANSS$SD <- rollingSD(ANSS$Price, h = 252)
AR$SD <- rollingSD(AR$Price, h = 252)
ANTM$SD <- rollingSD(ANTM$Price, h = 252)
AON$SD <- rollingSD(AON$Price, h = 252)
AAPL$SD <- rollingSD(AAPL$Price, h = 252)
ARMK$SD <- rollingSD(ARMK$Price, h = 252)
ACGL$SD <- rollingSD(ACGL$Price, h = 252)
T$SD <- rollingSD(T$Price, h = 252)
ADP$SD <- rollingSD(ADP$Price, h = 252)
AZO$SD <- rollingSD(AZO$Price, h = 252)
AVB$SD <- rollingSD(AVB$Price, h = 252)
AXS$SD <- rollingSD(AXS$Price, h = 252)
BXLT$SD <- rollingSD(BXLT$Price, h = 234)
BAX$SD <- rollingSD(BAX$Price, h = 252)
BDX$SD <- rollingSD(BDX$Price, h = 252)
BBBY$SD <- rollingSD(BBBY$Price, h = 252)
BRKB$SD <- rollingSD(BRKB$Price, h = 252)
BIIB$SD <- rollingSD(BIIB$Price, h = 252)
BLKFDS$SD <- rollingSD(BLKFDS$Price, h = 252)
BMC$SD <- rollingSD(BMC$Price, h = 252)
BXP$SD <- rollingSD(BXP$Price, h = 252)
BSX$SD <- rollingSD(BSX$Price, h = 252)
BMY$SD <- rollingSD(BMY$Price, h = 252)
BRX$SD <- rollingSD(BRX$Price, h = 252)
BR$SD <- rollingSD(BR$Price, h = 252)
BCR$SD <- rollingSD(BCR$Price, h = 252)
CA$SD <- rollingSD(CA$Price, h = 252)
COG$SD <- rollingSD(COG$Price, h = 252)
CDNS$SD <- rollingSD(CDNS$Price, h = 252)
CRC$SD <- rollingSD(CRC$Price, h = 252)
CPT$SD <- rollingSD(CPT$Price, h = 252)
CPB$SD <- rollingSD(CPB$Price, h = 252)
CAH$SD <- rollingSD(CAH$Price, h = 252)
CELG$SD <- rollingSD(CELG$Price, h = 252)
CTL$SD <- rollingSD(CTL$Price, h = 252)
CHRW$SD <- rollingSD(CHRW$Price, h = 252)
CHTR$SD <- rollingSD(CHTR$Price, h = 252)
CVX$SD <- rollingSD(CVX$Price, h = 252)
CMG$SD <- rollingSD(CMG$Price, h = 252)
CHD$SD <- rollingSD(CHD$Price, h = 252)
CI$SD <- rollingSD(CI$Price, h = 252)
CINF$SD <- rollingSD(CINF$Price, h = 252)
CTAS$SD <- rollingSD(CTAS$Price, h = 252)
CSCO$SD <- rollingSD(CSCO$Price, h = 252)
CLX$SD <- rollingSD(CLX$Price, h = 252)
CME$SD <- rollingSD(CME$Price, h = 252)
KO$SD <- rollingSD(KO$Price, h = 252)
COLE$SD <- rollingSD(COLE$Price, h = 161)
CL$SD <- rollingSD(CL$Price, h = 252)
CMCSA$SD <- rollingSD(CMCSA$Price, h = 252)
CMCSK$SD <- rollingSD(CMCSK$Price, h = 252)
CAG$SD <- rollingSD(CAG$Price, h = 252)
COP$SD <- rollingSD(COP$Price, h = 252)
ED$SD <- rollingSD(ED$Price, h = 252)
STZ$SD <- rollingSD(STZ$Price, h = 252)
COO$SD <- rollingSD(COO$Price, h = 252)
COST$SD <- rollingSD(COST$Price, h = 252)
COV$SD <- rollingSD(COV$Price, h = 252)
CCI$SD <- rollingSD(CCI$Price, h = 252)
CVS$SD <- rollingSD(CVS$Price, h = 252)
DHR$SD <- rollingSD(DHR$Price, h = 252)
DRI$SD <- rollingSD(DRI$Price, h = 252)
DVA$SD <- rollingSD(DVA$Price, h = 252)
DE$SD <- rollingSD(DE$Price, h = 252)
DLR$SD <- rollingSD(DLR$Price, h = 252)
DTV$SD <- rollingSD(DTV$Price, h = 252)
DG$SD <- rollingSD(DG$Price, h = 252)
DLTR$SD <- rollingSD(DLTR$Price, h = 252)
D$SD <- rollingSD(D$Price, h = 252)
DPS$SD <- rollingSD(DPS$Price, h = 252)
DUK$SD <- rollingSD(DUK$Price, h = 252)
DNB$SD <- rollingSD(DNB$Price, h = 252)
DD$SD <- rollingSD(DD$Price, h = 252)
EBAY$SD <- rollingSD(EBAY$Price, h = 252)
ECL$SD <- rollingSD(ECL$Price, h = 252)
EW$SD <- rollingSD(EW$Price, h = 252)
LLY$SD <- rollingSD(LLY$Price, h = 252)
EMC$SD <- rollingSD(EMC$Price, h = 252)
EGN$SD <- rollingSD(EGN$Price, h = 252)
EQT$SD <- rollingSD(EQT$Price, h = 252)
EFX$SD <- rollingSD(EFX$Price, h = 252)
EQR$SD <- rollingSD(EQR$Price, h = 252)
ESS$SD <- rollingSD(ESS$Price, h = 252)
RE$SD <- rollingSD(RE$Price, h = 252)
ES$SD <- rollingSD(ES$Price, h = 252)
EXPD$SD <- rollingSD(EXPD$Price, h = 252)
ESRX$SD <- rollingSD(ESRX$Price, h = 252)
EXR$SD <- rollingSD(EXR$Price, h = 252)
XOM$SD <- rollingSD(XOM$Price, h = 252)
FB$SD <- rollingSD(FB$Price, h = 252)
FDO$SD <- rollingSD(FDO$Price, h = 252)
FRT$SD <- rollingSD(FRT$Price, h = 252)
FNF$SD <- rollingSD(FNF$Price, h = 252)
FIS$SD <- rollingSD(FIS$Price, h = 252)
FRC$SD <- rollingSD(FRC$Price, h = 252)
FISV$SD <- rollingSD(FISV$Price, h = 252)
FL$SD <- rollingSD(FL$Price, h = 252)
FRX$SD <- rollingSD(FRX$Price, h = 252)
FTV$SD <- rollingSD(FTV$Price, h = 126)
FTR$SD <- rollingSD(FTR$Price, h = 252)
IT$SD <- rollingSD(IT$Price, h = 252)
GD$SD <- rollingSD(GD$Price, h = 252)
GGP$SD <- rollingSD(GGP$Price, h = 252)
GIS$SD <- rollingSD(GIS$Price, h = 252)
GPC$SD <- rollingSD(GPC$Price, h = 252)
GILD$SD <- rollingSD(GILD$Price, h = 252)
GR$SD <- rollingSD(GR$Price, h = 252)
HNZ$SD <- rollingSD(HNZ$Price, h = 252)
HCP$SD <- rollingSD(HCP$Price, h = 252)
HCN$SD <- rollingSD(HCN$Price, h = 252)
HSIC$SD <- rollingSD(HSIC$Price, h = 252)
HSY$SD <- rollingSD(HSY$Price, h = 252)
HOLX$SD <- rollingSD(HOLX$Price, h = 252)
HD$SD <- rollingSD(HD$Price, h = 252)
HRL$SD <- rollingSD(HRL$Price, h = 252)
HUM$SD <- rollingSD(HUM$Price, h = 252)
IHS$SD <- rollingSD(IHS$Price, h = 252)
INCO$SD <- rollingSD(INCO$Price, h = 252)
INTC$SD <- rollingSD(INTC$Price, h = 252)
IBM$SD <- rollingSD(IBM$Price, h = 252)
INTU$SD <- rollingSD(INTU$Price, h = 252)
ISRG$SD <- rollingSD(ISRG$Price, h = 252)
JBHT$SD <- rollingSD(JBHT$Price, h = 252)
SJM$SD <- rollingSD(SJM$Price, h = 252)
JNJ$SD <- rollingSD(JNJ$Price, h = 252)
K$SD <- rollingSD(K$Price, h = 252)
KMB$SD <- rollingSD(KMB$Price, h = 252)
KMI$SD <- rollingSD(KMI$Price, h = 252)
KMR$SD <- rollingSD(KMR$Price, h = 252)
KRFT$SD <- rollingSD(KRFT$Price, h = 252)
KFT$SD <- rollingSD(KFT$Price, h = 252)
LB$SD <- rollingSD(LB$Price, h = 252)
LH$SD <- rollingSD(LH$Price, h = 252)
LIFE$SD <- rollingSD(LIFE$Price, h = 252)
LLTC$SD <- rollingSD(LLTC$Price, h = 252)
LMT$SD <- rollingSD(LMT$Price, h = 252)
LOM$SD <- rollingSD(LOM$Price, h = 252)
LO$SD <- rollingSD(LO$Price, h = 252)
LOW$SD <- rollingSD(LOW$Price, h = 252)
MTB$SD <- rollingSD(MTB$Price, h = 252)
MAC$SD <- rollingSD(MAC$Price, h = 252)
MNK$SD <- rollingSD(MNK$Price, h = 252)
MKL$SD <- rollingSD(MKL$Price, h = 252)
MMC$SD <- rollingSD(MMC$Price, h = 252)
MA$SD <- rollingSD(MA$Price, h = 252)
MAT$SD <- rollingSD(MAT$Price, h = 252)
MKC$SD <- rollingSD(MKC$Price, h = 252)
MCD$SD <- rollingSD(MCD$Price, h = 252)
MCK$SD <- rollingSD(MCK$Price, h = 252)
MDT$SD <- rollingSD(MDT$Price, h = 252)
MRK$SD <- rollingSD(MRK$Price, h = 252)
MSFT$SD <- rollingSD(MSFT$Price, h = 252)
KTF$SD <- rollingSD(KTF$Price, h = 252)
MDLZ$SD <- rollingSD(MDLZ$Price, h = 252)
MON$SD <- rollingSD(MON$Price, h = 252)
MSI$SD <- rollingSD(MSI$Price, h = 252)
NNN$SD <- rollingSD(NNN$Price, h = 252)
NEM$SD <- rollingSD(NEM$Price, h = 252)
NWSA$SD <- rollingSD(NWSA$Price, h = 252)
NEE$SD <- rollingSD(NEE$Price, h = 252)
NLSN$SD <- rollingSD(NLSN$Price, h = 252)
NKE$SD <- rollingSD(NKE$Price, h = 252)
JWN$SD <- rollingSD(JWN$Price, h = 252)
NOC$SD <- rollingSD(NOC$Price, h = 252)
NST$SD <- rollingSD(NST$Price, h = 252)
ORLY$SD <- rollingSD(ORLY$Price, h = 252)
OXY$SD <- rollingSD(OXY$Price, h = 252)
OCR$SD <- rollingSD(OCR$Price, h = 252)
OMC$SD <- rollingSD(OMC$Price, h = 252)
ORCL$SD <- rollingSD(ORCL$Price, h = 252)
PRE$SD <- rollingSD(PRE$Price, h = 252)
PDCO$SD <- rollingSD(PDCO$Price, h = 252)
PAYX$SD <- rollingSD(PAYX$Price, h = 252)
PYPL$SD <- rollingSD(PYPL$Price, h = 252)
PBCT$SD <- rollingSD(PBCT$Price, h = 252)
POM$SD <- rollingSD(POM$Price, h = 252)
PEP$SD <- rollingSD(PEP$Price, h = 252)
PRGO$SD <- rollingSD(PRGO$Price, h = 252)
PETM$SD <- rollingSD(PETM$Price, h = 252)
PFE$SD <- rollingSD(PFE$Price, h = 252)
PCG$SD <- rollingSD(PCG$Price, h = 252)
PM$SD <- rollingSD(PM$Price, h = 252)
PSX$SD <- rollingSD(PSX$Price, h = 252)
PX$SD <- rollingSD(PX$Price, h = 252)
PCP$SD <- rollingSD(PCP$Price, h = 252)
PG$SD <- rollingSD(PG$Price, h = 252)
PGN$SD <- rollingSD(PGN$Price, h = 252)
PGR$SD <- rollingSD(PGR$Price, h = 252)
PSA$SD <- rollingSD(PSA$Price, h = 252)
QCI$SD <- rollingSD(QCI$Price, h = 252)
QCOM$SD <- rollingSD(QCOM$Price, h = 252)
DGX$SD <- rollingSD(DGX$Price, h = 252)
Q$SD <- rollingSD(Q$Price, h = 252)
RRC$SD <- rollingSD(RRC$Price, h = 252)
RTN$SD <- rollingSD(RTN$Price, h = 252)
O$SD <- rollingSD(O$Price, h = 252)
REG$SD <- rollingSD(REG$Price, h = 252)
RNR$SD <- rollingSD(RNR$Price, h = 252)
RSG$SD <- rollingSD(RSG$Price, h = 252)
RMD$SD <- rollingSD(RMD$Price, h = 252)
RAI$SD <- rollingSD(RAI$Price, h = 252)
ROST$SD <- rollingSD(ROST$Price, h = 252)
MHFI$SD <- rollingSD(MHFI$Price, h = 252)
LDOS$SD <- rollingSD(LDOS$Price, h = 252)
SBAC$SD <- rollingSD(SBAC$Price, h = 252)
SLB$SD <- rollingSD(SLB$Price, h = 252)
SNI$SD <- rollingSD(SNI$Price, h = 252)
SRE$SD <- rollingSD(SRE$Price, h = 252)
SHW$SD <- rollingSD(SHW$Price, h = 252)
SIAL$SD <- rollingSD(SIAL$Price, h = 252)
SPG$SD <- rollingSD(SPG$Price, h = 252)
SO$SD <- rollingSD(SO$Price, h = 252)
LUV$SD <- rollingSD(LUV$Price, h = 252)
SE$SD <- rollingSD(SE$Price, h = 252)
STJ$SD <- rollingSD(STJ$Price, h = 252)
SBUX$SD <- rollingSD(SBUX$Price, h = 252)
SRCL$SD <- rollingSD(SRCL$Price, h = 252)
SYK$SD <- rollingSD(SYK$Price, h = 252)
SYMC$SD <- rollingSD(SYMC$Price, h = 252)
SNPS$SD <- rollingSD(SNPS$Price, h = 252)
SYY$SD <- rollingSD(SYY$Price, h = 252)
TGT$SD <- rollingSD(TGT$Price, h = 252)
TXN$SD <- rollingSD(TXN$Price, h = 252)
TMO$SD <- rollingSD(TMO$Price, h = 252)
TJX$SD <- rollingSD(TJX$Price, h = 252)
TSS$SD <- rollingSD(TSS$Price, h = 252)
TRV$SD <- rollingSD(TRV$Price, h = 252)
UDR$SD <- rollingSD(UDR$Price, h = 252)
ULTA$SD <- rollingSD(ULTA$Price, h = 252)
UNP$SD <- rollingSD(UNP$Price, h = 252)
UPS$SD <- rollingSD(UPS$Price, h = 252)
UTX$SD <- rollingSD(UTX$Price, h = 252)
UNH$SD <- rollingSD(UNH$Price, h = 252)
UHS$SD <- rollingSD(UHS$Price, h = 252)
USB$SD <- rollingSD(USB$Price, h = 252)
USD$SD <- rollingSD(USD$Price, h = 252)
VAL$SD <- rollingSD(VAL$Price, h = 252)
VNTV$SD <- rollingSD(VNTV$Price, h = 252)
VAR$SD <- rollingSD(VAR$Price, h = 252)
VTR$SD <- rollingSD(VTR$Price, h = 252)
VRSN$SD <- rollingSD(VRSN$Price, h = 252)
VRSK$SD <- rollingSD(VRSK$Price, h = 252)
VZ$SD <- rollingSD(VZ$Price, h = 252)
VFC$SD <- rollingSD(VFC$Price, h = 252)
VISA$SD <- rollingSD(VISA$Price, h = 252)
V$SD <- rollingSD(V$Price, h = 252)
VMW$SD <- rollingSD(VMW$Price, h = 252)
VNO$SD <- rollingSD(VNO$Price, h = 252)
WMT$SD <- rollingSD(WMT$Price, h = 252)
DIS$SD <- rollingSD(DIS$Price, h = 252)
WCN$SD <- rollingSD(WCN$Price, h = 252)
WM$SD <- rollingSD(WM$Price, h = 252)
WAT$SD <- rollingSD(WAT$Price, h = 252)
WPI$SD <- rollingSD(WPI$Price, h = 252)
WEC$SD <- rollingSD(WEC$Price, h = 252)
WFC$SD <- rollingSD(WFC$Price, h = 252)
WR$SD <- rollingSD(WR$Price, h = 252)
WSH$SD <- rollingSD(WSH$Price, h = 252)
WLTW$SD <- rollingSD(WLTW$Price, h = 251)
WIN$SD <- rollingSD(WIN$Price, h = 252)
WRB$SD <- rollingSD(WRB$Price, h = 252)
GWW$SD <- rollingSD(GWW$Price, h = 252)
XEL$SD <- rollingSD(XEL$Price, h = 252)
YHOO$SD <- rollingSD(YHOO$Price, h = 252)
YUM$SD <- rollingSD(YUM$Price, h = 252)
ZAYO$SD <- rollingSD(ZAYO$Price, h = 252)
ZBH$SD <- rollingSD(ZBH$Price, h = 252)
ZTS$SD <- rollingSD(ZTS$Price, h = 252)



minvol_tickers_rolling_sd <- rbind(MMM,ABT,ABBV,ACN,CB,ACE,ACT,ATVI,ADBE,AAP,AET,GAS,AGNC,Y,AGN,ALL,GOOGL,GOOG,ALTR,MO,AEP,AMT,AWK,ABC,AMGN,APH,NLY,ANSS,AR,ANTM,AON,AAPL,ARMK,ACGL,T,ADP,AZO,AVB,AXS,BXLT,BAX,BDX,BBBY,BRKB,BIIB,BLKFDS,BMC,BXP,BSX,BMY,BRX,BR,BCR,CA,COG,CDNS,CRC,CPT,CPB,CAH,CELG,CTL,CHRW,CHTR,CVX,CMG,CHD,CI,CINF,CTAS,CSCO,CLX,CME,KO,COLE,CL,CMCSA,CMCSK,CAG,COP,ED,STZ,COO,COST,COV,CCI,CVS,DHR,DRI,DVA,DE,DLR,DTV,DG,DLTR,D,DPS,DUK,DNB,DD,EBAY,ECL,EW,LLY,EMC,EGN,EQT,EFX,EQR,ESS,RE,ES,EXPD,ESRX,EXR,XOM,FB,FDO,FRT,FNF,FIS,FRC,FISV,FL,FRX,FTV,FTR,IT,GD,GGP,GIS,GPC,GILD,GR,HNZ,HCP,HCN,HSIC,HSY,HOLX,HD,HRL,HUM,IHS,INCO,INTC,IBM,INTU,ISRG,JBHT,SJM,JNJ,K,KMB,KMI,KMR,KRFT,KFT,LB,LH,LIFE,LLTC,LMT,LOM,LO,LOW,MTB,MAC,MNK,MKL,MMC,MA,MAT,MKC,MCD,MCK,MDT,MRK,MSFT,KTF,MDLZ,MON,MSI,NNN,NEM,NWSA,NEE,NLSN,NKE,JWN,NOC,NST,ORLY,OXY,OCR,OMC,ORCL,PRE,PDCO,PAYX,PYPL,PBCT,POM,PEP,PRGO,PETM,PFE,PCG,PM,PSX,PX,PCP,PG,PGN,PGR,PSA,QCI,QCOM,DGX,Q,RRC,RTN,O,REG,RNR,RSG,RMD,RAI,ROST,MHFI,LDOS,SBAC,SLB,SNI,SRE,SHW,SIAL,SPG,SO,LUV,SE,STJ,SBUX,SRCL,SYK,SYMC,SNPS,SYY,TGT,TXN,TMO,TJX,TSS,TRV,UDR,ULTA,UNP,UPS,UTX,UNH,UHS,USB,USD,VAL,VNTV,VAR,VTR,VRSN,VRSK,VZ,VFC,VISA,V,VMW,VNO,WMT,DIS,WCN,WM,WAT,WPI,WEC,WFC,WR,WSH,WLTW,WIN,WRB,GWW,XEL,YHOO,YUM,ZAYO,ZBH,ZTS)



#Saving the separate ticjer files
devtools::use_data(AAP,overwrite = TRUE)
devtools::use_data(AAPL,overwrite = TRUE)
devtools::use_data(ABBV,overwrite = TRUE)
devtools::use_data(ABC,overwrite = TRUE)
devtools::use_data(ABT,overwrite = TRUE)
devtools::use_data(ACE,overwrite = TRUE)
devtools::use_data(ACGL,overwrite = TRUE)
devtools::use_data(ACN,overwrite = TRUE)
devtools::use_data(ACT,overwrite = TRUE)
devtools::use_data(ADBE,overwrite = TRUE)
devtools::use_data(ADP,overwrite = TRUE)
devtools::use_data(AEP,overwrite = TRUE)
devtools::use_data(AET,overwrite = TRUE)
devtools::use_data(AGN,overwrite = TRUE)
devtools::use_data(AGNC,overwrite = TRUE)
devtools::use_data(ALL,overwrite = TRUE)
devtools::use_data(ALTR,overwrite = TRUE)
devtools::use_data(AMGN,overwrite = TRUE)
devtools::use_data(AMT,overwrite = TRUE)
devtools::use_data(ANSS,overwrite = TRUE)
devtools::use_data(ANTM,overwrite = TRUE)
devtools::use_data(AON,overwrite = TRUE)
devtools::use_data(APH,overwrite = TRUE)
devtools::use_data(AR,overwrite = TRUE)
devtools::use_data(ARMK,overwrite = TRUE)
devtools::use_data(ATVI,overwrite = TRUE)
devtools::use_data(AVB,overwrite = TRUE)
devtools::use_data(AWK,overwrite = TRUE)
devtools::use_data(AXS,overwrite = TRUE)
devtools::use_data(AZO,overwrite = TRUE)
devtools::use_data(BAX,overwrite = TRUE)
devtools::use_data(BBBY,overwrite = TRUE)
devtools::use_data(BCR,overwrite = TRUE)
devtools::use_data(BDX,overwrite = TRUE)
devtools::use_data(BIIB,overwrite = TRUE)
devtools::use_data(BLKFDS,overwrite = TRUE)
devtools::use_data(BMC,overwrite = TRUE)
devtools::use_data(BMY,overwrite = TRUE)
devtools::use_data(BR,overwrite = TRUE)
devtools::use_data(BRKB,overwrite = TRUE)
devtools::use_data(BRX,overwrite = TRUE)
devtools::use_data(BSX,overwrite = TRUE)
devtools::use_data(BXLT,overwrite = TRUE)
devtools::use_data(BXP,overwrite = TRUE)
devtools::use_data(CA,overwrite = TRUE)
devtools::use_data(CAG,overwrite = TRUE)
devtools::use_data(CAH,overwrite = TRUE)
devtools::use_data(CB,overwrite = TRUE)
devtools::use_data(CCI,overwrite = TRUE)
devtools::use_data(CDNS,overwrite = TRUE)
devtools::use_data(CELG,overwrite = TRUE)
devtools::use_data(CHD,overwrite = TRUE)
devtools::use_data(CHRW,overwrite = TRUE)
devtools::use_data(CHTR,overwrite = TRUE)
devtools::use_data(CI,overwrite = TRUE)
devtools::use_data(CINF,overwrite = TRUE)
devtools::use_data(CL,overwrite = TRUE)
devtools::use_data(CLX,overwrite = TRUE)
devtools::use_data(CMCSA,overwrite = TRUE)
devtools::use_data(CMCSK,overwrite = TRUE)
devtools::use_data(CME,overwrite = TRUE)
devtools::use_data(CMG,overwrite = TRUE)
devtools::use_data(COG,overwrite = TRUE)
devtools::use_data(COLE,overwrite = TRUE)
devtools::use_data(COO,overwrite = TRUE)
devtools::use_data(COP,overwrite = TRUE)
devtools::use_data(COST,overwrite = TRUE)
devtools::use_data(COV,overwrite = TRUE)
devtools::use_data(CPB,overwrite = TRUE)
devtools::use_data(CPT,overwrite = TRUE)
devtools::use_data(CRC,overwrite = TRUE)
devtools::use_data(CSCO,overwrite = TRUE)
devtools::use_data(CTAS,overwrite = TRUE)
devtools::use_data(CTL,overwrite = TRUE)
devtools::use_data(CVS,overwrite = TRUE)
devtools::use_data(CVX,overwrite = TRUE)
devtools::use_data(D,overwrite = TRUE)
devtools::use_data(DD,overwrite = TRUE)
devtools::use_data(DE,overwrite = TRUE)
devtools::use_data(DG,overwrite = TRUE)
devtools::use_data(DGX,overwrite = TRUE)
devtools::use_data(DHR,overwrite = TRUE)
devtools::use_data(DIS,overwrite = TRUE)
devtools::use_data(DLR,overwrite = TRUE)
devtools::use_data(DLTR,overwrite = TRUE)
devtools::use_data(DNB,overwrite = TRUE)
devtools::use_data(DPS,overwrite = TRUE)
devtools::use_data(DRI,overwrite = TRUE)
devtools::use_data(DTV,overwrite = TRUE)
devtools::use_data(DUK,overwrite = TRUE)
devtools::use_data(DVA,overwrite = TRUE)
devtools::use_data(EBAY,overwrite = TRUE)
devtools::use_data(ECL,overwrite = TRUE)
devtools::use_data(ED,overwrite = TRUE)
devtools::use_data(EFX,overwrite = TRUE)
devtools::use_data(EGN,overwrite = TRUE)
devtools::use_data(EMC,overwrite = TRUE)
devtools::use_data(EQR,overwrite = TRUE)
devtools::use_data(EQT,overwrite = TRUE)
devtools::use_data(ES,overwrite = TRUE)
devtools::use_data(ESRX,overwrite = TRUE)
devtools::use_data(ESS,overwrite = TRUE)
devtools::use_data(EW,overwrite = TRUE)
devtools::use_data(EXPD,overwrite = TRUE)
devtools::use_data(EXR,overwrite = TRUE)
devtools::use_data(FB,overwrite = TRUE)
devtools::use_data(FDO,overwrite = TRUE)
devtools::use_data(FIS,overwrite = TRUE)
devtools::use_data(FISV,overwrite = TRUE)
devtools::use_data(FL,overwrite = TRUE)
devtools::use_data(FNF,overwrite = TRUE)
devtools::use_data(FRC,overwrite = TRUE)
devtools::use_data(FRT,overwrite = TRUE)
devtools::use_data(FRX,overwrite = TRUE)
devtools::use_data(FTR,overwrite = TRUE)
devtools::use_data(FTV,overwrite = TRUE)
devtools::use_data(GAS,overwrite = TRUE)
devtools::use_data(GD,overwrite = TRUE)
devtools::use_data(GGP,overwrite = TRUE)
devtools::use_data(GILD,overwrite = TRUE)
devtools::use_data(GIS,overwrite = TRUE)
devtools::use_data(GOOG,overwrite = TRUE)
devtools::use_data(GOOGL,overwrite = TRUE)
devtools::use_data(GPC,overwrite = TRUE)
devtools::use_data(GR,overwrite = TRUE)
devtools::use_data(GWW,overwrite = TRUE)
devtools::use_data(HCN,overwrite = TRUE)
devtools::use_data(HCP,overwrite = TRUE)
devtools::use_data(HD,overwrite = TRUE)
devtools::use_data(HNZ,overwrite = TRUE)
devtools::use_data(HOLX,overwrite = TRUE)
devtools::use_data(HRL,overwrite = TRUE)
devtools::use_data(HSIC,overwrite = TRUE)
devtools::use_data(HSY,overwrite = TRUE)
devtools::use_data(HUM,overwrite = TRUE)
devtools::use_data(IBM,overwrite = TRUE)
devtools::use_data(IHS,overwrite = TRUE)
devtools::use_data(INCO,overwrite = TRUE)
devtools::use_data(INTC,overwrite = TRUE)
devtools::use_data(INTU,overwrite = TRUE)
devtools::use_data(ISRG,overwrite = TRUE)
devtools::use_data(IT,overwrite = TRUE)
devtools::use_data(JBHT,overwrite = TRUE)
devtools::use_data(JNJ,overwrite = TRUE)
devtools::use_data(JWN,overwrite = TRUE)
devtools::use_data(K,overwrite = TRUE)
devtools::use_data(KFT,overwrite = TRUE)
devtools::use_data(KMB,overwrite = TRUE)
devtools::use_data(KMI,overwrite = TRUE)
devtools::use_data(KMR,overwrite = TRUE)
devtools::use_data(KO,overwrite = TRUE)
devtools::use_data(KRFT,overwrite = TRUE)
devtools::use_data(KTF,overwrite = TRUE)
devtools::use_data(LB,overwrite = TRUE)
devtools::use_data(LDOS,overwrite = TRUE)
devtools::use_data(LH,overwrite = TRUE)
devtools::use_data(LIFE,overwrite = TRUE)
devtools::use_data(LLTC,overwrite = TRUE)
devtools::use_data(LLY,overwrite = TRUE)
devtools::use_data(LMT,overwrite = TRUE)
devtools::use_data(LO,overwrite = TRUE)
devtools::use_data(LOM,overwrite = TRUE)
devtools::use_data(LOW,overwrite = TRUE)
devtools::use_data(LUV,overwrite = TRUE)
devtools::use_data(MA,overwrite = TRUE)
devtools::use_data(MAC,overwrite = TRUE)
devtools::use_data(MAT,overwrite = TRUE)
devtools::use_data(MCD,overwrite = TRUE)
devtools::use_data(MCK,overwrite = TRUE)
devtools::use_data(MDLZ,overwrite = TRUE)
devtools::use_data(MDT,overwrite = TRUE)
devtools::use_data(MHFI,overwrite = TRUE)
devtools::use_data(MKC,overwrite = TRUE)
devtools::use_data(MKL,overwrite = TRUE)
devtools::use_data(MMC,overwrite = TRUE)
devtools::use_data(MMM,overwrite = TRUE)
devtools::use_data(MNK,overwrite = TRUE)
devtools::use_data(MO,overwrite = TRUE)
devtools::use_data(MON,overwrite = TRUE)
devtools::use_data(MRK,overwrite = TRUE)
devtools::use_data(MSFT,overwrite = TRUE)
devtools::use_data(MSI,overwrite = TRUE)
devtools::use_data(MTB,overwrite = TRUE)
devtools::use_data(NEE,overwrite = TRUE)
devtools::use_data(NEM,overwrite = TRUE)
devtools::use_data(NKE,overwrite = TRUE)
devtools::use_data(NLSN,overwrite = TRUE)
devtools::use_data(NLY,overwrite = TRUE)
devtools::use_data(NNN,overwrite = TRUE)
devtools::use_data(NOC,overwrite = TRUE)
devtools::use_data(NST,overwrite = TRUE)
devtools::use_data(NWSA,overwrite = TRUE)
devtools::use_data(O,overwrite = TRUE)
devtools::use_data(OCR,overwrite = TRUE)
devtools::use_data(OMC,overwrite = TRUE)
devtools::use_data(ORCL,overwrite = TRUE)
devtools::use_data(ORLY,overwrite = TRUE)
devtools::use_data(OXY,overwrite = TRUE)
devtools::use_data(PAYX,overwrite = TRUE)
devtools::use_data(PBCT,overwrite = TRUE)
devtools::use_data(PCG,overwrite = TRUE)
devtools::use_data(PCP,overwrite = TRUE)
devtools::use_data(PDCO,overwrite = TRUE)
devtools::use_data(PEP,overwrite = TRUE)
devtools::use_data(PETM,overwrite = TRUE)
devtools::use_data(PFE,overwrite = TRUE)
devtools::use_data(PG,overwrite = TRUE)
devtools::use_data(PGN,overwrite = TRUE)
devtools::use_data(PGR,overwrite = TRUE)
devtools::use_data(PM,overwrite = TRUE)
devtools::use_data(POM,overwrite = TRUE)
devtools::use_data(PRE,overwrite = TRUE)
devtools::use_data(PRGO,overwrite = TRUE)
devtools::use_data(PSA,overwrite = TRUE)
devtools::use_data(PSX,overwrite = TRUE)
devtools::use_data(PX,overwrite = TRUE)
devtools::use_data(PYPL,overwrite = TRUE)
devtools::use_data(Q,overwrite = TRUE)
devtools::use_data(QCI,overwrite = TRUE)
devtools::use_data(QCOM,overwrite = TRUE)
devtools::use_data(RAI,overwrite = TRUE)
devtools::use_data(RE,overwrite = TRUE)
devtools::use_data(REG,overwrite = TRUE)
devtools::use_data(RMD,overwrite = TRUE)
devtools::use_data(RNR,overwrite = TRUE)
devtools::use_data(ROST,overwrite = TRUE)
devtools::use_data(RRC,overwrite = TRUE)
devtools::use_data(RSG,overwrite = TRUE)
devtools::use_data(RTN,overwrite = TRUE)
devtools::use_data(SBAC,overwrite = TRUE)
devtools::use_data(SBUX,overwrite = TRUE)
devtools::use_data(SE,overwrite = TRUE)
devtools::use_data(SHW,overwrite = TRUE)
devtools::use_data(SIAL,overwrite = TRUE)
devtools::use_data(SJM,overwrite = TRUE)
devtools::use_data(SLB,overwrite = TRUE)
devtools::use_data(SNI,overwrite = TRUE)
devtools::use_data(SNPS,overwrite = TRUE)
devtools::use_data(SO,overwrite = TRUE)
devtools::use_data(SPG,overwrite = TRUE)
devtools::use_data(SRCL,overwrite = TRUE)
devtools::use_data(SRE,overwrite = TRUE)
devtools::use_data(STJ,overwrite = TRUE)
devtools::use_data(STZ,overwrite = TRUE)
devtools::use_data(SYK,overwrite = TRUE)
devtools::use_data(SYMC,overwrite = TRUE)
devtools::use_data(SYY,overwrite = TRUE)
devtools::use_data(T,overwrite = TRUE)
devtools::use_data(TGT,overwrite = TRUE)
devtools::use_data(TJX,overwrite = TRUE)
devtools::use_data(TMO,overwrite = TRUE)
devtools::use_data(TRV,overwrite = TRUE)
devtools::use_data(TSS,overwrite = TRUE)
devtools::use_data(TXN,overwrite = TRUE)
devtools::use_data(UDR,overwrite = TRUE)
devtools::use_data(UHS,overwrite = TRUE)
devtools::use_data(ULTA,overwrite = TRUE)
devtools::use_data(UNH,overwrite = TRUE)
devtools::use_data(UNP,overwrite = TRUE)
devtools::use_data(UPS,overwrite = TRUE)
devtools::use_data(USB,overwrite = TRUE)
devtools::use_data(USD,overwrite = TRUE)
devtools::use_data(UTX,overwrite = TRUE)
devtools::use_data(V,overwrite = TRUE)
devtools::use_data(VAL,overwrite = TRUE)
devtools::use_data(VAR,overwrite = TRUE)
devtools::use_data(VFC,overwrite = TRUE)
devtools::use_data(VISA,overwrite = TRUE)
devtools::use_data(VMW,overwrite = TRUE)
devtools::use_data(VNO,overwrite = TRUE)
devtools::use_data(VNTV,overwrite = TRUE)
devtools::use_data(VRSK,overwrite = TRUE)
devtools::use_data(VRSN,overwrite = TRUE)
devtools::use_data(VTR,overwrite = TRUE)
devtools::use_data(VZ,overwrite = TRUE)
devtools::use_data(WAT,overwrite = TRUE)
devtools::use_data(WCN,overwrite = TRUE)
devtools::use_data(WEC,overwrite = TRUE)
devtools::use_data(WFC,overwrite = TRUE)
devtools::use_data(WIN,overwrite = TRUE)
devtools::use_data(WLTW,overwrite = TRUE)
devtools::use_data(WM,overwrite = TRUE)
devtools::use_data(WMT,overwrite = TRUE)
devtools::use_data(WPI,overwrite = TRUE)
devtools::use_data(WR,overwrite = TRUE)
devtools::use_data(WRB,overwrite = TRUE)
devtools::use_data(WSH,overwrite = TRUE)
devtools::use_data(XEL,overwrite = TRUE)
devtools::use_data(XOM,overwrite = TRUE)
devtools::use_data(Y,overwrite = TRUE)
devtools::use_data(YHOO,overwrite = TRUE)
devtools::use_data(YUM,overwrite = TRUE)
devtools::use_data(ZAYO,overwrite = TRUE)
devtools::use_data(ZBH,overwrite = TRUE)
devtools::use_data(ZTS,overwrite = TRUE)



devtools::use_data(minvol_tickers_rolling_sd,overwrite = TRUE)

